### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by olaven**
Adding support for Docker 🐳 
Thank you for this project!
I have spent some time modifying it, and this suits my needs. 

Let me know if I broke something!

@olaven

### CODE REVIEW

**Comment by AkhileshNS** [comment]
Hey thanks for your work. I'll check it out and finalize the request by tomorrow

**Comment by AkhileshNS** [comment]
Hey sorry for replying so late (especially when I said I would reply earlier). But I just need you to add a few changes before I can finalize the pull request:-

1. In the index.js file, can you uncomment the `execSync("git fetch --prune --unshallow");` command. Unfortunately this is still needed since regular heroku-deploy functions need the repo to be unshallow. I don't know if this is the case for docker as well. I'll try to do some testing on this at the earliest. 

2. Secondly before you can import the `useDocker` env variable, you'll need to declare it in the action.yml file:-
```yml
name: "Deploy to Heroku"
description: "Deploy an app to Heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  heroku_app_name:
    description: "The appname to use for deploying/updating"
    required: true
  buildpack:
    description: "An optional buildpack to use when creating the heroku application"
  branch:
    description: "The branch that you would like to deploy to Heroku"
    default: "HEAD"
  dontuseforce:
    description: "Set this to true if you don't want to use --force when switching branches"
    default: false
  useDocker: # <- ADD THIS
    description: "Set this to true if using Docker containers to deploy" # <- ADD THIS
    default: false # <- ADD THIS
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "index.js"
```

and I guess if possible try to use lowercase letters for the env variable. So `usedocker` instead of `useDocker`. This one really doesn't matter as much but if you can, it just keeps things a little more consistent.

**Comment by olaven** [comment]
No worries! Thank you for taking such a thorough look. 
I will make these changes as soon as soon as I can. 

1: Sure 😃 It does not seem to be needed for Docker.
2: I was not aware of this; this is my first look at Github Actions. My bad. 
3: consistency is important, I agree :-)

**Comment by olaven** [comment]
I also refactored the functions in an attempt to make them more consistent with the style of `createCatFile` 😄

**Comment by AkhileshNS** [comment]
Thanks again for your contribution. I'm working on a new feature right now, once that's added, I'll create a new release of the action which includes the docker support you've coded in. For now, if you want to use the action with docker support, just use `akhileshns/heroku-deploy@master` instead of `akhileshns/heroku-deploy@2.0.2`. I'll add this to the documentation by this afternoon

**Comment by olaven** [comment]
Thank you for letting me contribute! 😄

**Pull request merged**
