### PR TITLE
Option for app located in subdirectory

### LINKED ISSUE #7: App located in subdirectory
When using your action I get
```
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz        
remote:                
remote:  !     ERROR: Application not supported by 'heroku/nodejs' buildpack        
remote:  !             
remote:  !     The 'heroku/nodejs' buildpack is set on this application, but was        
remote:  !     unable to detect a Node.js codebase.        
remote:  !                 
remote:  !     A Node.js app on Heroku requires a 'package.json' at the root of        
remote:  !     the directory structure. 
```

because my NodeJS app is in a API folder.

Is there anyway to use ```git push subtree``` with this action?

Thanks in advance.

### PR DESCRIPTION
**Pull request by meszarosdezso**
Fixes #7

### CODE REVIEW

**Comment by meszarosdezso** [comment]
Based on top of 3.0.0, because master branch caused timeout while running the workflow.

**Comment by AkhileshNS** [comment]
Hey, thanks for your contribution. I'll run your changes through some tests to make sure its working fine and accept. 

Additionally, if you're adding a new variable (appdir) as part of the action, you'll need to make changes to the `action.yml` file as well. Go through the file and you'll understand what I mean.

(Sidenote. I've been working on some optimizations on the master branch, probably why it was giving you the timeout errors. Now that I think about it, it isn't good practice anyway and I'll move that kind of work to its own branch so future pull requests won't run into those kind of problems)

**Comment by meszarosdezso** [comment]
I added the option to the ```action.yml``` in this commit! ( Line 27 ) 🙂

**Comment by AkhileshNS** [comment]
Hey thanks again for your contribution. Sorry it took as long as it did

**Pull request merged**
